#
### Sass Lint File ###
#
# Documentation for the sass-lint Linters is available at:
# https://github.com/sasstools/sass-lint/tree/master/docs/rules
# 0: rule turn off
# 1: warning
# 2: error

# Linter Options
options:
  merge-default-rules: false
  formatter: stylish

# File Options
files:
  include: "src/sass/**/*.s+(a|c)ss"
  ignore:
    - "node_modules"

# Rule Configuration
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0

  brace-style:
    style: "stroustrup"
    allow-single-line: false

  # Mixins
  mixins-before-declarations:
    - 2
    - exclude:
        - "iota-breakpoint"

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks:
    - 2
    - ignore-single-line-rulesets: 0
    - include: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 1
  no-empty-rulesets: 2
  no-extends: 1
  no-ids: 2
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - extra-properties:
        - "*font-family"
        - "*height"
        - "interpolation-mode"
        - "*margin-left"
        - "*vertical-align"
        - "*width"
  no-qualifying-elements: 0
  no-trailing-zero: 2
  no-transition-all: 0
  no-url-protocols: 2
  no-vendor-prefixes: 0
  no-warn: 2
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  nesting-depth:
    - 2
    - max-depth: 4
  bem-depth:
    - 0
    - max_elements: 1

  # Name Formats
  class-name-format:
    - 2
    - convention: hyphenatedbem
  mixin-name-format:
    - 2
    - convention: hyphenatedbem
  placeholder-name-format:
    - 2
    - convention: hyphenatedbem
  hex-notation:
    - 2
    - style: lowercase # or uppercase
  function-name-format: 2
  id-name-format: 2
  variable-name-format: 2
  indentation:
    - 2
    - size: 4
  leading-zero: 2
  border-zero:
    - 2
    - convention: none # or `zero`
  quotes:
    - 2
    - style: single
  shorthand-values: 2
  url-quotes: 0
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 0
  space-around-operator: 0

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
